### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by itroeix** [jsonmona/twilight-cpp#1]
I don't know much about cmake, so I could be wrong, but when compiling with the command ```cmake -S . -B ./build``` it says that everything is correct, but when I enter the ```build/bin/client``` and ```build/bin/server``` folder, it only are the dlls, is there a way to create an executable?

**Comment by jsonmona** [comment]
What platform and what compiler are you using?

**Comment by itroeix** [comment]
Windows 10, cmake windows version, qt 6.4.2 (mingw_64)

**Comment by jsonmona** [comment]
You need to use MSVC. Install Visual Studio 2019 Community or later, and use that compiler instead.

Note that as mentioned on README, this project is being rewritten in Rust. It's not a direct rewrite, but more like "delete everything and start from the scratch". The C++ version you're seeing will not be updated in any way. I'm confident that I'll be able to upload the Rust version within the next month.

Feel free to ask any questions about the C++ version in the meantime!

**Comment by itroeix** [comment]
I have already created the executables, but when executing the client some dlls are missing:
Qt6Widgetsd.dll
Qt6Guid.dll
Qt6Cored.dll
I didn't find the dlls anywhere, i guess the compiler didn't create the qt dll files.

**Comment by jsonmona** [comment]
I see. They're Qt6 binary, and it is normal they're not created. You can find those inside Qt6 installation. For example, `C:\Qt\6.3.2\msvc2019_64\bin\Qt6Cored.dll`.

**Comment by itroeix** [comment]
I put all the necessary dlls, now it shows this error, I think the problem is that it creates it in debug mode, but I'm not sure, I'm going to investigate the code a little more.
![client_pr16we2SqH](https://user-images.githubusercontent.com/54476100/222824188-c29e7619-4120-4f2b-9164-89dbf8685945.png)

**Comment by jsonmona** [comment]
That's weird. Can you try running `windeployqt.exe` manually? The relevant line in `CMakeFiles.txt` is:
https://github.com/jsonmona/twilight/blob/a54df27c9de69dffa79182f40e970b9e92347555/src/CMakeLists.txt#L319-L332

Which means executing `windeployqt.exe --verbose 0 client.exe` in the directory where `client.exe` is in. Try removing the verbose flag when you execute it manually.

**Comment by itroeix** [comment]
Thanks! the client works, but when running the server it stays at "Starting twilight remote desktop server..."
![image](https://user-images.githubusercontent.com/54476100/224160126-a7c03a99-c089-4d16-a2b9-1d184400c123.png)

**Comment by jsonmona** [comment]
It is working as expected. The server does not have GUI. Could you close the issue if it's resolved?

**Comment by itroeix** [comment]
Works! but it seems to not have mouse support, but I will try to implement it, thanks for the help.

**Comment by itroeix** [comment]
Could you in the rust version implement mouse and keyboard support? Thanks for creating this project!

**Comment by jsonmona** [comment]
No. In fact, the Rust version isn't feature parity with the C++ version. I'd love it to be, but I'm busy with serving Korean military service for next 2 years, which is mandatory for every Korean man. So I have only little time to work on personal projects.

I'm going to archive this repository once I push the Rust version. (Notice the `-cpp` in the project name) You may create fork if you want to, but I'm not going to manage this project anymore.

Closing as solved.
